#- hosts: webservers

#  tasks:
#  - name: Installation de python 3
#    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python-minimal)

- hosts: webservers
  
  roles:
  - server
  - php
  - mysql
  - wordpress
