---

- name: Mise à jour du serveur (apt update)
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Installation des paquets nécessaires à Wordpress
  ansible.builtin.apt:
    pkg:
    - apache2
    - mariadb-server
    - mariadb-client
    - php-mysql
    - php
    - libapache2-mod-php
    - pip
  become: true

- name: Installation d'un paquet python (pymysql)
  ansible.builtin.pip:
    name: pymysql
  become: true
